version: "2"

services:
    frontend:
        image: tomaskral/kompose-demo-frontend:kubecon2016
        ports:
            - 8080:8080

    backend:
        image: tomaskral/kompose-demo-backend:kubecon2016
        ports:
            - 3000:3000
        environment: 
            MONGODB_PASSWORD: pass
            MONGODB_USER: user
            MONGODB_DATABASE: db
            MONGODB_SERVER: mongodb:27017
 
    mongodb:
        image: centos/mongodb-26-centos7
        ports:
            - 27017:27017
        environment: 
            MONGODB_PASSWORD: pass
            MONGODB_USER: user
            MONGODB_DATABASE: db
            MONGODB_ADMIN_PASSWORD: root
            
