version: "2"

services:

    backend:
        image: tomaskral/kompose-demo-backend
        ports:
            - 3000:3000

    frontend:
        image: tomaskral/kompose-demo-frontend
        ports:
            - 8080:8080
        environment:
            API_URL: http://${BACKEND_HOST}/api


